project:
  type: website
  output-dir: docs

website:
  title: "w-weiqin's Website"
  search: false
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: internship.qmd
        text: Project
      - href: viz.qmd
        text: Data Viz
      - href: reflection.qmd
        text: Reflection

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true